
pipeline {
    agent any
    tools {
        maven 'Maven'
        jdk 'jdk8'
		}
	stages {
        stage('Checkout') {
           steps { 
				git url: 'https://github.com/habsh/microservice1.git', credentialsId: 'habsh', branch: 'master'
		   }
        }

        stage('Build') {
		steps {
            bat 'mvn clean install'
			}
        }

        stage('Image') {
			steps {
					cd ./account-service 
					def app = docker build "account-service:accounts"
					docker push "account-service:accounts"
					
				}
        }

        stage ('Run') {
		steps {
            docker image run -p 2222:2222 -h account --name account --link discovery
			}
        }

        stage ('Final') {
		steps {
            build job: 'customer-service-pipeline', wait: false
			}
        }      

    }

}
